{#
    rename_audit
    ============
    Scans target/manifest.json (generated by `dbt compile`) to identify
    every documented column that matches the rename map defined in
    `var('column_renames')`.

    No warehouse connection required.

    Usage:
      dbt compile
      dbt run-operation rename_audit

    Output:
      A report printed to stdout listing:
        - model file path
        - current column name
        - proposed new column name
#}

{% macro rename_audit() %}

    {% set rename_map = var('column_renames', {}) %}

    {% if rename_map | length == 0 %}
        {{ log("  No renames defined. Set `column_renames` var in dbt_project.yml.", info=True) }}
        {{ return([]) }}
    {% endif %}

    {# Load manifest.json produced by dbt compile #}
    {% set manifest_raw = load_file_contents('target/manifest.json') %}

    {% if manifest_raw is none %}
        {{ log("  target/manifest.json not found. Run `dbt compile` first.", info=True) }}
        {{ return([]) }}
    {% endif %}

    {% set manifest = fromjson(manifest_raw) %}
    {% set audit_results = [] %}

    {{ log("", info=True) }}
    {{ log("═══════════════════════════════════════════════════════════════", info=True) }}
    {{ log("  COLUMN RENAME AUDIT REPORT", info=True) }}
    {{ log("═══════════════════════════════════════════════════════════════", info=True) }}
    {{ log("", info=True) }}
    {{ log("  Rename map:", info=True) }}
    {% for old_name, new_name in rename_map.items() %}
        {{ log("    " ~ old_name ~ " → " ~ new_name, info=True) }}
    {% endfor %}
    {{ log("", info=True) }}
    {{ log("───────────────────────────────────────────────────────────────", info=True) }}
    {{ log("  %-50s %-25s %-25s" | format("MODEL", "CURRENT COLUMN", "NEW COLUMN"), info=True) }}
    {{ log("───────────────────────────────────────────────────────────────", info=True) }}

    {% for node_id, node in manifest.nodes.items() %}
        {% if node.resource_type in ['model', 'seed', 'snapshot'] %}
            {% for col_name in node.columns %}
                {% set col_lower = col_name | lower %}
                {% if col_lower in rename_map %}
                    {% set new_name = rename_map[col_lower] %}
                    {{ log("  %-50s %-25s %-25s" | format(node.path, col_name, new_name), info=True) }}
                    {% do audit_results.append({
                        'model': node.path,
                        'current_column': col_name,
                        'new_column': new_name
                    }) %}
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endfor %}

    {% if audit_results | length == 0 %}
        {{ log("  No documented columns match the rename map.", info=True) }}
        {{ log("  Columns used as SQL aliases may not be documented in schema.yml.", info=True) }}
        {{ log("  The Python script will still find and rename them in your SQL files.", info=True) }}
    {% endif %}

    {{ log("───────────────────────────────────────────────────────────────", info=True) }}
    {{ log("  Total: " ~ audit_results | length ~ " documented column(s) across " ~ (audit_results | map(attribute='model') | list | unique | list | length) ~ " model(s)", info=True) }}
    {{ log("═══════════════════════════════════════════════════════════════", info=True) }}
    {{ log("", info=True) }}
    {{ log("  Next step: preview all file changes with the Python script:", info=True) }}
    {{ log("    python dbt_packages/dbt_rename_column/scripts/rename_columns.py --project-dir . --dry-run", info=True) }}
    {{ log("", info=True) }}

    {{ return(audit_results) }}

{% endmacro %}
